# Generated by Django 4.2.6 on 2023-10-24 15:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_donation_is_taken'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instytucja'},
        ),
    ]
