# Generated by Django 4.2.6 on 2023-10-24 15:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0004_alter_institution_options'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='institution',
            options={'verbose_name': 'Instytucja', 'verbose_name_plural': 'Instytucje'},
        ),
    ]
